const GIT_HUB_RESULT = '''
{
"total_count": 1088,
"incomplete_results": false,
"items": [
{
"login": "natanael",
"id": 76589,
"node_id": "MDQ6VXNlcjc2NTg5",
"avatar_url": "https://avatars.githubusercontent.com/u/76589?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanael",
"html_url": "https://github.com/natanael",
"followers_url": "https://api.github.com/users/natanael/followers",
"following_url": "https://api.github.com/users/natanael/following{/other_user}",
"gists_url": "https://api.github.com/users/natanael/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanael/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanael/subscriptions",
"organizations_url": "https://api.github.com/users/natanael/orgs",
"repos_url": "https://api.github.com/users/natanael/repos",
"events_url": "https://api.github.com/users/natanael/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanael/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "Natanaelvich",
"id": 52014318,
"node_id": "MDQ6VXNlcjUyMDE0MzE4",
"avatar_url": "https://avatars.githubusercontent.com/u/52014318?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Natanaelvich",
"html_url": "https://github.com/Natanaelvich",
"followers_url": "https://api.github.com/users/Natanaelvich/followers",
"following_url": "https://api.github.com/users/Natanaelvich/following{/other_user}",
"gists_url": "https://api.github.com/users/Natanaelvich/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Natanaelvich/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Natanaelvich/subscriptions",
"organizations_url": "https://api.github.com/users/Natanaelvich/orgs",
"repos_url": "https://api.github.com/users/Natanaelvich/repos",
"events_url": "https://api.github.com/users/Natanaelvich/events{/privacy}",
"received_events_url": "https://api.github.com/users/Natanaelvich/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "NatanaelAntonioli",
"id": 13460524,
"node_id": "MDQ6VXNlcjEzNDYwNTI0",
"avatar_url": "https://avatars.githubusercontent.com/u/13460524?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/NatanaelAntonioli",
"html_url": "https://github.com/NatanaelAntonioli",
"followers_url": "https://api.github.com/users/NatanaelAntonioli/followers",
"following_url": "https://api.github.com/users/NatanaelAntonioli/following{/other_user}",
"gists_url": "https://api.github.com/users/NatanaelAntonioli/gists{/gist_id}",
"starred_url": "https://api.github.com/users/NatanaelAntonioli/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/NatanaelAntonioli/subscriptions",
"organizations_url": "https://api.github.com/users/NatanaelAntonioli/orgs",
"repos_url": "https://api.github.com/users/NatanaelAntonioli/repos",
"events_url": "https://api.github.com/users/NatanaelAntonioli/events{/privacy}",
"received_events_url": "https://api.github.com/users/NatanaelAntonioli/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanaelsimoes",
"id": 1112479,
"node_id": "MDQ6VXNlcjExMTI0Nzk=",
"avatar_url": "https://avatars.githubusercontent.com/u/1112479?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanaelsimoes",
"html_url": "https://github.com/natanaelsimoes",
"followers_url": "https://api.github.com/users/natanaelsimoes/followers",
"following_url": "https://api.github.com/users/natanaelsimoes/following{/other_user}",
"gists_url": "https://api.github.com/users/natanaelsimoes/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanaelsimoes/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanaelsimoes/subscriptions",
"organizations_url": "https://api.github.com/users/natanaelsimoes/orgs",
"repos_url": "https://api.github.com/users/natanaelsimoes/repos",
"events_url": "https://api.github.com/users/natanaelsimoes/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanaelsimoes/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "ncopa",
"id": 66357,
"node_id": "MDQ6VXNlcjY2MzU3",
"avatar_url": "https://avatars.githubusercontent.com/u/66357?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/ncopa",
"html_url": "https://github.com/ncopa",
"followers_url": "https://api.github.com/users/ncopa/followers",
"following_url": "https://api.github.com/users/ncopa/following{/other_user}",
"gists_url": "https://api.github.com/users/ncopa/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ncopa/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ncopa/subscriptions",
"organizations_url": "https://api.github.com/users/ncopa/orgs",
"repos_url": "https://api.github.com/users/ncopa/repos",
"events_url": "https://api.github.com/users/ncopa/events{/privacy}",
"received_events_url": "https://api.github.com/users/ncopa/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanaelpantoja",
"id": 91941,
"node_id": "MDQ6VXNlcjkxOTQx",
"avatar_url": "https://avatars.githubusercontent.com/u/91941?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanaelpantoja",
"html_url": "https://github.com/natanaelpantoja",
"followers_url": "https://api.github.com/users/natanaelpantoja/followers",
"following_url": "https://api.github.com/users/natanaelpantoja/following{/other_user}",
"gists_url": "https://api.github.com/users/natanaelpantoja/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanaelpantoja/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanaelpantoja/subscriptions",
"organizations_url": "https://api.github.com/users/natanaelpantoja/orgs",
"repos_url": "https://api.github.com/users/natanaelpantoja/repos",
"events_url": "https://api.github.com/users/natanaelpantoja/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanaelpantoja/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanaeljr",
"id": 9396162,
"node_id": "MDQ6VXNlcjkzOTYxNjI=",
"avatar_url": "https://avatars.githubusercontent.com/u/9396162?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanaeljr",
"html_url": "https://github.com/natanaeljr",
"followers_url": "https://api.github.com/users/natanaeljr/followers",
"following_url": "https://api.github.com/users/natanaeljr/following{/other_user}",
"gists_url": "https://api.github.com/users/natanaeljr/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanaeljr/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanaeljr/subscriptions",
"organizations_url": "https://api.github.com/users/natanaeljr/orgs",
"repos_url": "https://api.github.com/users/natanaeljr/repos",
"events_url": "https://api.github.com/users/natanaeljr/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanaeljr/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "Nata07",
"id": 13895506,
"node_id": "MDQ6VXNlcjEzODk1NTA2",
"avatar_url": "https://avatars.githubusercontent.com/u/13895506?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Nata07",
"html_url": "https://github.com/Nata07",
"followers_url": "https://api.github.com/users/Nata07/followers",
"following_url": "https://api.github.com/users/Nata07/following{/other_user}",
"gists_url": "https://api.github.com/users/Nata07/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Nata07/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Nata07/subscriptions",
"organizations_url": "https://api.github.com/users/Nata07/orgs",
"repos_url": "https://api.github.com/users/Nata07/repos",
"events_url": "https://api.github.com/users/Nata07/events{/privacy}",
"received_events_url": "https://api.github.com/users/Nata07/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanael-silvamt",
"id": 25402851,
"node_id": "MDQ6VXNlcjI1NDAyODUx",
"avatar_url": "https://avatars.githubusercontent.com/u/25402851?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanael-silvamt",
"html_url": "https://github.com/natanael-silvamt",
"followers_url": "https://api.github.com/users/natanael-silvamt/followers",
"following_url": "https://api.github.com/users/natanael-silvamt/following{/other_user}",
"gists_url": "https://api.github.com/users/natanael-silvamt/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanael-silvamt/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanael-silvamt/subscriptions",
"organizations_url": "https://api.github.com/users/natanael-silvamt/orgs",
"repos_url": "https://api.github.com/users/natanael-silvamt/repos",
"events_url": "https://api.github.com/users/natanael-silvamt/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanael-silvamt/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanael-oliveira",
"id": 51293075,
"node_id": "MDQ6VXNlcjUxMjkzMDc1",
"avatar_url": "https://avatars.githubusercontent.com/u/51293075?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanael-oliveira",
"html_url": "https://github.com/natanael-oliveira",
"followers_url": "https://api.github.com/users/natanael-oliveira/followers",
"following_url": "https://api.github.com/users/natanael-oliveira/following{/other_user}",
"gists_url": "https://api.github.com/users/natanael-oliveira/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanael-oliveira/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanael-oliveira/subscriptions",
"organizations_url": "https://api.github.com/users/natanael-oliveira/orgs",
"repos_url": "https://api.github.com/users/natanael-oliveira/repos",
"events_url": "https://api.github.com/users/natanael-oliveira/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanael-oliveira/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "sudo-give-me-coffee",
"id": 20757825,
"node_id": "MDQ6VXNlcjIwNzU3ODI1",
"avatar_url": "https://avatars.githubusercontent.com/u/20757825?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/sudo-give-me-coffee",
"html_url": "https://github.com/sudo-give-me-coffee",
"followers_url": "https://api.github.com/users/sudo-give-me-coffee/followers",
"following_url": "https://api.github.com/users/sudo-give-me-coffee/following{/other_user}",
"gists_url": "https://api.github.com/users/sudo-give-me-coffee/gists{/gist_id}",
"starred_url": "https://api.github.com/users/sudo-give-me-coffee/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/sudo-give-me-coffee/subscriptions",
"organizations_url": "https://api.github.com/users/sudo-give-me-coffee/orgs",
"repos_url": "https://api.github.com/users/sudo-give-me-coffee/repos",
"events_url": "https://api.github.com/users/sudo-give-me-coffee/events{/privacy}",
"received_events_url": "https://api.github.com/users/sudo-give-me-coffee/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "NatanaelSaymon",
"id": 59451978,
"node_id": "MDQ6VXNlcjU5NDUxOTc4",
"avatar_url": "https://avatars.githubusercontent.com/u/59451978?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/NatanaelSaymon",
"html_url": "https://github.com/NatanaelSaymon",
"followers_url": "https://api.github.com/users/NatanaelSaymon/followers",
"following_url": "https://api.github.com/users/NatanaelSaymon/following{/other_user}",
"gists_url": "https://api.github.com/users/NatanaelSaymon/gists{/gist_id}",
"starred_url": "https://api.github.com/users/NatanaelSaymon/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/NatanaelSaymon/subscriptions",
"organizations_url": "https://api.github.com/users/NatanaelSaymon/orgs",
"repos_url": "https://api.github.com/users/NatanaelSaymon/repos",
"events_url": "https://api.github.com/users/NatanaelSaymon/events{/privacy}",
"received_events_url": "https://api.github.com/users/NatanaelSaymon/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "white-gecko",
"id": 1018168,
"node_id": "MDQ6VXNlcjEwMTgxNjg=",
"avatar_url": "https://avatars.githubusercontent.com/u/1018168?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/white-gecko",
"html_url": "https://github.com/white-gecko",
"followers_url": "https://api.github.com/users/white-gecko/followers",
"following_url": "https://api.github.com/users/white-gecko/following{/other_user}",
"gists_url": "https://api.github.com/users/white-gecko/gists{/gist_id}",
"starred_url": "https://api.github.com/users/white-gecko/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/white-gecko/subscriptions",
"organizations_url": "https://api.github.com/users/white-gecko/orgs",
"repos_url": "https://api.github.com/users/white-gecko/repos",
"events_url": "https://api.github.com/users/white-gecko/events{/privacy}",
"received_events_url": "https://api.github.com/users/white-gecko/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "NatanaelLemos",
"id": 6020778,
"node_id": "MDQ6VXNlcjYwMjA3Nzg=",
"avatar_url": "https://avatars.githubusercontent.com/u/6020778?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/NatanaelLemos",
"html_url": "https://github.com/NatanaelLemos",
"followers_url": "https://api.github.com/users/NatanaelLemos/followers",
"following_url": "https://api.github.com/users/NatanaelLemos/following{/other_user}",
"gists_url": "https://api.github.com/users/NatanaelLemos/gists{/gist_id}",
"starred_url": "https://api.github.com/users/NatanaelLemos/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/NatanaelLemos/subscriptions",
"organizations_url": "https://api.github.com/users/NatanaelLemos/orgs",
"repos_url": "https://api.github.com/users/NatanaelLemos/repos",
"events_url": "https://api.github.com/users/NatanaelLemos/events{/privacy}",
"received_events_url": "https://api.github.com/users/NatanaelLemos/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanaelsirqueira",
"id": 13697898,
"node_id": "MDQ6VXNlcjEzNjk3ODk4",
"avatar_url": "https://avatars.githubusercontent.com/u/13697898?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanaelsirqueira",
"html_url": "https://github.com/natanaelsirqueira",
"followers_url": "https://api.github.com/users/natanaelsirqueira/followers",
"following_url": "https://api.github.com/users/natanaelsirqueira/following{/other_user}",
"gists_url": "https://api.github.com/users/natanaelsirqueira/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanaelsirqueira/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanaelsirqueira/subscriptions",
"organizations_url": "https://api.github.com/users/natanaelsirqueira/orgs",
"repos_url": "https://api.github.com/users/natanaelsirqueira/repos",
"events_url": "https://api.github.com/users/natanaelsirqueira/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanaelsirqueira/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "Natanaelmar7",
"id": 90940882,
"node_id": "MDQ6VXNlcjkwOTQwODgy",
"avatar_url": "https://avatars.githubusercontent.com/u/90940882?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Natanaelmar7",
"html_url": "https://github.com/Natanaelmar7",
"followers_url": "https://api.github.com/users/Natanaelmar7/followers",
"following_url": "https://api.github.com/users/Natanaelmar7/following{/other_user}",
"gists_url": "https://api.github.com/users/Natanaelmar7/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Natanaelmar7/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Natanaelmar7/subscriptions",
"organizations_url": "https://api.github.com/users/Natanaelmar7/orgs",
"repos_url": "https://api.github.com/users/Natanaelmar7/repos",
"events_url": "https://api.github.com/users/Natanaelmar7/events{/privacy}",
"received_events_url": "https://api.github.com/users/Natanaelmar7/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanaelblemos",
"id": 56853912,
"node_id": "MDQ6VXNlcjU2ODUzOTEy",
"avatar_url": "https://avatars.githubusercontent.com/u/56853912?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanaelblemos",
"html_url": "https://github.com/natanaelblemos",
"followers_url": "https://api.github.com/users/natanaelblemos/followers",
"following_url": "https://api.github.com/users/natanaelblemos/following{/other_user}",
"gists_url": "https://api.github.com/users/natanaelblemos/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanaelblemos/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanaelblemos/subscriptions",
"organizations_url": "https://api.github.com/users/natanaelblemos/orgs",
"repos_url": "https://api.github.com/users/natanaelblemos/repos",
"events_url": "https://api.github.com/users/natanaelblemos/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanaelblemos/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "nmcardoso",
"id": 12160840,
"node_id": "MDQ6VXNlcjEyMTYwODQw",
"avatar_url": "https://avatars.githubusercontent.com/u/12160840?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/nmcardoso",
"html_url": "https://github.com/nmcardoso",
"followers_url": "https://api.github.com/users/nmcardoso/followers",
"following_url": "https://api.github.com/users/nmcardoso/following{/other_user}",
"gists_url": "https://api.github.com/users/nmcardoso/gists{/gist_id}",
"starred_url": "https://api.github.com/users/nmcardoso/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/nmcardoso/subscriptions",
"organizations_url": "https://api.github.com/users/nmcardoso/orgs",
"repos_url": "https://api.github.com/users/nmcardoso/repos",
"events_url": "https://api.github.com/users/nmcardoso/events{/privacy}",
"received_events_url": "https://api.github.com/users/nmcardoso/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanaelfneto",
"id": 17500218,
"node_id": "MDQ6VXNlcjE3NTAwMjE4",
"avatar_url": "https://avatars.githubusercontent.com/u/17500218?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanaelfneto",
"html_url": "https://github.com/natanaelfneto",
"followers_url": "https://api.github.com/users/natanaelfneto/followers",
"following_url": "https://api.github.com/users/natanaelfneto/following{/other_user}",
"gists_url": "https://api.github.com/users/natanaelfneto/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanaelfneto/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanaelfneto/subscriptions",
"organizations_url": "https://api.github.com/users/natanaelfneto/orgs",
"repos_url": "https://api.github.com/users/natanaelfneto/repos",
"events_url": "https://api.github.com/users/natanaelfneto/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanaelfneto/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanaelphp",
"id": 2786131,
"node_id": "MDQ6VXNlcjI3ODYxMzE=",
"avatar_url": "https://avatars.githubusercontent.com/u/2786131?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanaelphp",
"html_url": "https://github.com/natanaelphp",
"followers_url": "https://api.github.com/users/natanaelphp/followers",
"following_url": "https://api.github.com/users/natanaelphp/following{/other_user}",
"gists_url": "https://api.github.com/users/natanaelphp/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanaelphp/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanaelphp/subscriptions",
"organizations_url": "https://api.github.com/users/natanaelphp/orgs",
"repos_url": "https://api.github.com/users/natanaelphp/repos",
"events_url": "https://api.github.com/users/natanaelphp/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanaelphp/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "DEXTERNATAN",
"id": 1324863,
"node_id": "MDQ6VXNlcjEzMjQ4NjM=",
"avatar_url": "https://avatars.githubusercontent.com/u/1324863?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/DEXTERNATAN",
"html_url": "https://github.com/DEXTERNATAN",
"followers_url": "https://api.github.com/users/DEXTERNATAN/followers",
"following_url": "https://api.github.com/users/DEXTERNATAN/following{/other_user}",
"gists_url": "https://api.github.com/users/DEXTERNATAN/gists{/gist_id}",
"starred_url": "https://api.github.com/users/DEXTERNATAN/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/DEXTERNATAN/subscriptions",
"organizations_url": "https://api.github.com/users/DEXTERNATAN/orgs",
"repos_url": "https://api.github.com/users/DEXTERNATAN/repos",
"events_url": "https://api.github.com/users/DEXTERNATAN/events{/privacy}",
"received_events_url": "https://api.github.com/users/DEXTERNATAN/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "NatanSiilva",
"id": 66763596,
"node_id": "MDQ6VXNlcjY2NzYzNTk2",
"avatar_url": "https://avatars.githubusercontent.com/u/66763596?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/NatanSiilva",
"html_url": "https://github.com/NatanSiilva",
"followers_url": "https://api.github.com/users/NatanSiilva/followers",
"following_url": "https://api.github.com/users/NatanSiilva/following{/other_user}",
"gists_url": "https://api.github.com/users/NatanSiilva/gists{/gist_id}",
"starred_url": "https://api.github.com/users/NatanSiilva/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/NatanSiilva/subscriptions",
"organizations_url": "https://api.github.com/users/NatanSiilva/orgs",
"repos_url": "https://api.github.com/users/NatanSiilva/repos",
"events_url": "https://api.github.com/users/NatanSiilva/events{/privacy}",
"received_events_url": "https://api.github.com/users/NatanSiilva/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanaelmota1",
"id": 54650675,
"node_id": "MDQ6VXNlcjU0NjUwNjc1",
"avatar_url": "https://avatars.githubusercontent.com/u/54650675?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanaelmota1",
"html_url": "https://github.com/natanaelmota1",
"followers_url": "https://api.github.com/users/natanaelmota1/followers",
"following_url": "https://api.github.com/users/natanaelmota1/following{/other_user}",
"gists_url": "https://api.github.com/users/natanaelmota1/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanaelmota1/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanaelmota1/subscriptions",
"organizations_url": "https://api.github.com/users/natanaelmota1/orgs",
"repos_url": "https://api.github.com/users/natanaelmota1/repos",
"events_url": "https://api.github.com/users/natanaelmota1/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanaelmota1/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "n4tm",
"id": 63219861,
"node_id": "MDQ6VXNlcjYzMjE5ODYx",
"avatar_url": "https://avatars.githubusercontent.com/u/63219861?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/n4tm",
"html_url": "https://github.com/n4tm",
"followers_url": "https://api.github.com/users/n4tm/followers",
"following_url": "https://api.github.com/users/n4tm/following{/other_user}",
"gists_url": "https://api.github.com/users/n4tm/gists{/gist_id}",
"starred_url": "https://api.github.com/users/n4tm/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/n4tm/subscriptions",
"organizations_url": "https://api.github.com/users/n4tm/orgs",
"repos_url": "https://api.github.com/users/n4tm/repos",
"events_url": "https://api.github.com/users/n4tm/events{/privacy}",
"received_events_url": "https://api.github.com/users/n4tm/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanaelfonseca",
"id": 2238272,
"node_id": "MDQ6VXNlcjIyMzgyNzI=",
"avatar_url": "https://avatars.githubusercontent.com/u/2238272?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanaelfonseca",
"html_url": "https://github.com/natanaelfonseca",
"followers_url": "https://api.github.com/users/natanaelfonseca/followers",
"following_url": "https://api.github.com/users/natanaelfonseca/following{/other_user}",
"gists_url": "https://api.github.com/users/natanaelfonseca/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanaelfonseca/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanaelfonseca/subscriptions",
"organizations_url": "https://api.github.com/users/natanaelfonseca/orgs",
"repos_url": "https://api.github.com/users/natanaelfonseca/repos",
"events_url": "https://api.github.com/users/natanaelfonseca/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanaelfonseca/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanael-araujo",
"id": 492542,
"node_id": "MDQ6VXNlcjQ5MjU0Mg==",
"avatar_url": "https://avatars.githubusercontent.com/u/492542?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanael-araujo",
"html_url": "https://github.com/natanael-araujo",
"followers_url": "https://api.github.com/users/natanael-araujo/followers",
"following_url": "https://api.github.com/users/natanael-araujo/following{/other_user}",
"gists_url": "https://api.github.com/users/natanael-araujo/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanael-araujo/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanael-araujo/subscriptions",
"organizations_url": "https://api.github.com/users/natanael-araujo/orgs",
"repos_url": "https://api.github.com/users/natanael-araujo/repos",
"events_url": "https://api.github.com/users/natanael-araujo/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanael-araujo/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "NatanaelNeto",
"id": 37716720,
"node_id": "MDQ6VXNlcjM3NzE2NzIw",
"avatar_url": "https://avatars.githubusercontent.com/u/37716720?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/NatanaelNeto",
"html_url": "https://github.com/NatanaelNeto",
"followers_url": "https://api.github.com/users/NatanaelNeto/followers",
"following_url": "https://api.github.com/users/NatanaelNeto/following{/other_user}",
"gists_url": "https://api.github.com/users/NatanaelNeto/gists{/gist_id}",
"starred_url": "https://api.github.com/users/NatanaelNeto/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/NatanaelNeto/subscriptions",
"organizations_url": "https://api.github.com/users/NatanaelNeto/orgs",
"repos_url": "https://api.github.com/users/NatanaelNeto/repos",
"events_url": "https://api.github.com/users/NatanaelNeto/events{/privacy}",
"received_events_url": "https://api.github.com/users/NatanaelNeto/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "natanaelvieirab",
"id": 49008314,
"node_id": "MDQ6VXNlcjQ5MDA4MzE0",
"avatar_url": "https://avatars.githubusercontent.com/u/49008314?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/natanaelvieirab",
"html_url": "https://github.com/natanaelvieirab",
"followers_url": "https://api.github.com/users/natanaelvieirab/followers",
"following_url": "https://api.github.com/users/natanaelvieirab/following{/other_user}",
"gists_url": "https://api.github.com/users/natanaelvieirab/gists{/gist_id}",
"starred_url": "https://api.github.com/users/natanaelvieirab/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/natanaelvieirab/subscriptions",
"organizations_url": "https://api.github.com/users/natanaelvieirab/orgs",
"repos_url": "https://api.github.com/users/natanaelvieirab/repos",
"events_url": "https://api.github.com/users/natanaelvieirab/events{/privacy}",
"received_events_url": "https://api.github.com/users/natanaelvieirab/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "Natanaelescobar26",
"id": 90202321,
"node_id": "MDQ6VXNlcjkwMjAyMzIx",
"avatar_url": "https://avatars.githubusercontent.com/u/90202321?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Natanaelescobar26",
"html_url": "https://github.com/Natanaelescobar26",
"followers_url": "https://api.github.com/users/Natanaelescobar26/followers",
"following_url": "https://api.github.com/users/Natanaelescobar26/following{/other_user}",
"gists_url": "https://api.github.com/users/Natanaelescobar26/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Natanaelescobar26/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Natanaelescobar26/subscriptions",
"organizations_url": "https://api.github.com/users/Natanaelescobar26/orgs",
"repos_url": "https://api.github.com/users/Natanaelescobar26/repos",
"events_url": "https://api.github.com/users/Natanaelescobar26/events{/privacy}",
"received_events_url": "https://api.github.com/users/Natanaelescobar26/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "Natanael-Acero",
"id": 55499367,
"node_id": "MDQ6VXNlcjU1NDk5MzY3",
"avatar_url": "https://avatars.githubusercontent.com/u/55499367?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Natanael-Acero",
"html_url": "https://github.com/Natanael-Acero",
"followers_url": "https://api.github.com/users/Natanael-Acero/followers",
"following_url": "https://api.github.com/users/Natanael-Acero/following{/other_user}",
"gists_url": "https://api.github.com/users/Natanael-Acero/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Natanael-Acero/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Natanael-Acero/subscriptions",
"organizations_url": "https://api.github.com/users/Natanael-Acero/orgs",
"repos_url": "https://api.github.com/users/Natanael-Acero/repos",
"events_url": "https://api.github.com/users/Natanael-Acero/events{/privacy}",
"received_events_url": "https://api.github.com/users/Natanael-Acero/received_events",
"type": "User",
"site_admin": false,
"score": 1
}
]
}
''';
